### ISSUE TITLE
December is shown but data not available.

### ISSUE THREAD

**Issue by DJxLaurens** [NickHuijgen01/inflatie-calculator#10]
When I select december from the dropdown menu. And I want to change my "bedrag" value then it set back the previous month (November). Looks like a bug. Maybe the data is still not available for december, but why do you already show this month if the data is not available for calculation?

PLEASE FIX!

**Comment by NickHuijgen** [comment]
Intentional. All months are show for consistency, when the user selects an invalid month the month will be reset to the latest valid month upon changing the jaar/bedrag inputs.

**Comment by NickHuijgen** [comment]
I don't agree. The month only changes when the user makes an action, and before the user makes the action it's clear that the selected data is invalid. I also think it would be incosistent to have different months greyed out per year. If you think you can do better, feel free to make a PR.
